[package]
name = "WaitUntil"
version = "0.1.0"
authors = ["SmuSmu"]

[dependencies]
time = "0.1"

[dependencies.clap]
version = "~2.26.0"
default-features = false
 
# Cherry-pick the features you'd like to use
# Maybe Later
features = [  ]